export const STORING_ARTICLES = "STORING_ARTICLES";
export const LOGGING_EMAIL = "LOGGING_EMAIL";
export const LOGGING_PASSWORD = "LOGGING_PASSWORD";
export const SETTING_USER = "SETTING_USER";
export const EDITING_ARTICLE = "EDITING_ARTICLE";
export const EDITING_TEXT = "EDITING_TEXT";
export const EDITING_HEADLINE = "EDITING_HEADLINE";
export const POSTING_ARTICLE = "POSTING_ARTICLE";
